### ISSUE TITLE
"Borreload Dragon" and "Interdimensional Matter Transporter"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#202]
> Q:
At the start of the Damage Step, when my Varreload Dragon attacks my opponent’s Firewall Dragon, I activate the effect of Varreload Dragon and take control of Firewall Dragon. During the next turn, if activate Interdimensional Matter Transporter and banish Firewall Dragon, what happens during the End Phase?
A:
In this scenario, upon reaching your End Phase, Firewall Dragon will return to your side of the field, but it will immediately return to its owner’s control. (Also, Firewall Dragon will not be sent to the Graveyard by the effect of Varreload Dragon.)

Currently, control of Firewall is retained, which is incorrect.

@NaimSantos :
> I am not sure what causes this.
But it looks like Borreloads control should only be until the end phase of th next turn... even though the text doesnt say that
Using  Duel.GetControl(tc,tp,PHASE_END,2,zone) causes an error when the monster returns

[Puzzle](https://cdn.discordapp.com/attachments/291708361752313866/679619539205357580/Borreload_puzzle_1.lua)

Originally reported 19/02/2020 by @NaimSantos

**Comment by kevinlul** [comment]
Regression introduced in fb76d65b02b472eb6348b6fd1803c246faedf680 because the fix applied in f284c244cd2d03f5de1eaf61f718e4fa7e66ef41 causes #331.

**Comment by pyrQ** [comment]
Just noting that this ruling doesn't make too much sense considering that Borreload's control switch should be permanent (disregarding the "send it to the GY" part which isn't directly tied to the control switch).

Nevertheless, it's fixed here: https://github.com/ProjectIgnis/CardScripts/commit/5e56dfd6f1b54778743be54baf2872256035aa35
The fix is a bit crude but it works.
