### ISSUE TITLE
Unable to target a banished "Spellbook Library of the Crescent" with "Spellbook of the Master"

### ISSUE THREAD

**Issue by kevinlul** [ProjectIgnis/CardScripts#328]
Ruling
> Q: Can I target a Spellbook Library of the Crescent in my Graveyard with Spellbook of the Master?

> A: You can target Spellbook Library of the Crescent with Spellbook of the Master. (In that case, the effect is applied normally.) However, if you activated a Spell Card this turn other than a "Spellbook" Spell Card, you cannot target Spellbook Library of the Crescent with Spellbook of the Master.

[Puzzle](https://cdn.discordapp.com/attachments/705222140609298483/706597256782151680/Teste_Spellbook_of_Crescent.lua) demonstrating that "Spellbook of the Master" is never allowed to be activated, incorrectly.

Reported May 3 by @NaimSantos

**Comment by TheRazgriz** [comment]
Isn't this because Master targets in the GY, not a banished card? The puzzle has no cards in the GY for Master to target.

**Comment by edo9300** [comment]
The issue is when before using master you activate upstart. If you activated upstart, then you shoduln't be able to use master and target crescent.

**Comment by TheRazgriz** [comment]
Ah, I see. I thought for some reason the puzzle was focused Master not being able to be activated ever.

**Comment by pyrQ** [comment]
Finally this silly ruling has been reverted:
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12799&request_locale=ja
`Q:
If I have activated a non-"Spellbook" Spell Card this turn, can I target [Spellbook Library of the Crescent](https://db.ygorganization.com/card#10318) using [Spellbook of the Master](https://db.ygorganization.com/card#10421)?
A:
Yes, you can.

The effect of [Spellbook of the Master](https://db.ygorganization.com/card#10421) only applies the effect resolution of the targeted "Spellbook" Normal Spell. Since『You cannot activate any Spell Cards the turn you activate this card, except "Spellbook" Spell Cards.』is a requirement for activating the card [Spellbook Library of the Crescent](https://db.ygorganization.com/card#10318), not part of that card's effect, it is irrelevant to the effect of [Spellbook of the Master](https://db.ygorganization.com/card#10421).

Therefore, you can apply the effect of [Spellbook Library of the Crescent](https://db.ygorganization.com/card#10318) using [Spellbook of the Master](https://db.ygorganization.com/card#10421) even if you have activated a non-"Spellbook" Spell Card previously. Additionally, it is possible to activate non-"Spellbook" Spell Cards after doing so.

This also applies to [Spellbook Library of the Heliosphere](https://db.ygorganization.com/card#10357).`
