### ISSUE TITLE
T.G. gear zombie does not trigger T.G. warwolf 

### ISSUE THREAD

**Issue by C0DE-GENESIS** [ProjectIgnis/CardScripts#549]
when i special summon t.g. gear zombie by it's own effect and i have t.g. warwolf in my hand, t.g. warwolf doesn't activate it's effect that special summon itself

**Comment by pyrQ** [comment]
>  .. Special Summon this card from your hand, then the targeted monster loses 1000 ATK.
In "do A, then do B", "A" and "B" do not happen at the same time.
> When a Level 4 or lower monster(s) is Special Summoned (except during the Damage Step): You can..
Since this is a "When" optional Trigger effect, the last thing that happens must be its condition being fulfilled and that is not the case here. This has been colloquially called "missing the timing", you can read more about it here:
[https://yugipedia.com/wiki/If..._You_Can_VS_When..._You_Can](https://yugipedia.com/wiki/If..._You_Can_VS_When..._You_Can)

Also, if you look at the repository's "Contributing" section [here](https://github.com/ProjectIgnis/CardScripts#contributing), you will find this, so please follow it in the future.
> Please keep all bug reports and questions on Discord; do NOT open an issue or pull request for this purpose.
